# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a95a7944-7883-4cf2-8a45-ac05b4b8584f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2556-5398";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

   # OpenGl & GPU Drivers
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };
   services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    powerManagement.finegrained = false;
    open = false;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };
   hardware.nvidia.prime = {
    sync.enable = true;

    # integrated
     intelBusId = "PCI:0:2:0";

    # dedicated
    nvidiaBusId = "PCI:1:0:0";
  };
  environment.systemPackages = [ pkgs.headsetcontrol ];
  services.udev.packages = [ pkgs.headsetcontrol ];
  systemd.services.headset-light-off = {
    description = "Continuously turn off headset lights";
    wantedBy = [ "multi-user.target" ];

    script = ''
      while true; do
        ${pkgs.headsetcontrol}/bin/headsetcontrol -l 0
        sleep 3
      done
    '';

    serviceConfig = {
      Type = "simple";
      Restart = "always";
      RestartSec = 1;
    };
  };
}
